name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: go mod tidy
        run: go mod tidy

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.3"

      - name: Test
        run: go test -v ./...
